# Generated by Django 3.1.2 on 2020-11-03 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Seccion', models.CharField(max_length=50)),
                ('Contenido', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Imagen', models.ImageField(upload_to='Online_garage_store')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto_usuario',
                'verbose_name_plural': 'Productos_usuario',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.ImageField(upload_to='Online_garage_store')),
                ('Edad', models.IntegerField()),
                ('Sexo', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Domicilio', models.CharField(max_length=70)),
                ('Usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Venta_descrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Online_garage_store.user_product')),
                ('Vendedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Online_garage_store.vendedor')),
            ],
            options={
                'verbose_name': 'Usuario_Venta_descrip',
                'verbose_name_plural': 'Usuario_Venta_descrip',
            },
        ),
        migrations.CreateModel(
            name='User_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Precio_IVA', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Vendedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Online_garage_store.vendedor')),
                ('Venta_desc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Online_garage_store.user_venta_descrip')),
            ],
            options={
                'verbose_name': 'Venta_usuario',
                'verbose_name_plural': 'Ventas_usuario',
            },
        ),
        migrations.AddField(
            model_name='user_product',
            name='Vendedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Online_garage_store.vendedor'),
        ),
        migrations.CreateModel(
            name='User_Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField()),
                ('Fecha', models.DateField()),
                ('Entregado', models.BooleanField()),
                ('Cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Vendedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Online_garage_store.vendedor')),
                ('Venta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Online_garage_store.user_venta')),
            ],
            options={
                'verbose_name': 'Envio_usuario',
                'verbose_name_plural': 'Envios_usuario',
            },
        ),
    ]
