# Generated by Django 3.1.2 on 2020-11-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
