# Generated by Django 3.1.2 on 2020-10-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nucleo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
