# Generated by Django 3.1.2 on 2020-11-23 02:42

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Contenido', models.TextField()),
                ('Imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now_add=True)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.users')),
                ('Categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorial.categoria')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriales',
            },
        ),
    ]
