# Generated by Django 3.1.2 on 2020-11-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '__first__'),
        ('Blog', '0002_auto_20201027_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.users'),
        ),
    ]
